- .github/buildomat/jobs/test-ddm-trio-v1-server.sh
- .github/buildomat/jobs/test-ddm-trio-v1-transit.sh
- .github/buildomat/test-ddm-common.sh
- ddm/src/discovery.rs
- ddm/src/exchange.rs
- ddm/src/sm.rs
- tests/src/ddm.rs
This PR now covers backward compatibility with version one of the ddm exchange protocol.
Ddm has two protocols, a router discovery protocol and a prefix exchange protocol. The tunnel routing updates did not change the discovery protocol - and that protocol carries an 8-bit version in it. I updated the exchange client/server code to speak either v1 or v2 of the protocol based on what the peer advertised in the discovery phase. I also added backward compatibility tests to CI.
> backwards compatibility with ddm protocol version 1

- bgp/src/dispatcher.rs
- mgadm/src/static_routing.rs
- mgd/src/static_admin.rs
- rdb/src/db.rs
- fixes #171
- makes `remove_nexthop4` symmetric with `set_nexthop4` with regard to static/persistent updates.
- fixes `mgadm` making the wrong API call on static route removal
- also: stops the BGP dispatcher from going into a tight error loop when it can't bind
> Fix remove-static-v4 API call

- Cargo.lock
- ddm/Cargo.toml
- ddm/src/db.rs
- ddm/src/exchange.rs
- ddmadm/src/main.rs
- mg-lower/src/ddm.rs
- mg-lower/src/lib.rs
- mgd/src/bfd_admin.rs
- rdb/src/db.rs
- tests/src/ddm.rs
This change makes it possible for operators of Oxide racks to transition to/from BFD without downtime.
In traditional BFD/static-routing setups, when a BFD session associated with the nexthop of a route enters the `down` state, that route is removed from the data plane routing tables. This means there is no graceful way to light up a BFD session, since we have to pick one end of the session to start first, and it will detect that the other side is down and start removing all the routes associated with the corresponding nexthop.
There are a few solutions to this problem. For example, the approach taken by FRR is to separate enabling BFD's upper half that implements the protocol, from the lower half that modifies the data plane routing tables. This works well for bootstrapping BFD without …
> Graceful transition to/from BFD-based networks

- Cargo.lock
- Cargo.toml
- bgp/Cargo.toml
- bgp/src/messages.rs
- bgp/src/session.rs
- ddm-admin-client/Cargo.toml
- ddm-admin-client/src/lib.rs
- ddm/Cargo.toml
- ddm/src/admin.rs
- ddm/src/db.rs
- ddm/src/exchange.rs
- ddm/src/sm.rs
- ddm/src/sys.rs
- ddmadm/src/main.rs
- mg-admin-client/Cargo.toml
- mg-admin-client/src/lib.rs
- mg-common/Cargo.toml
- mg-common/src/lib.rs
- mg-common/src/net.rs
- mgd/src/admin.rs
- mgd/src/bgp_admin.rs
- openapi/mg-admin.json
- Fixes #101 
Adds a simple in-memory queue for incoming and outgoing messages, and an API call to retrieve them. The queue size is limited to 1024 messages in each direction. This is meant as a debugging tool and is not meant to be a persistent historian.
> implement bgp message tracking

- ddmd/src/main.rs
- mgd/src/main.rs
- smf/mgd_method_script.sh
If these are not provided, we will not start an `oxstats` server.
Part of fixing https://github.com/oxidecomputer/omicron/issues/5318
> mgd and mg-ddm: make rack-uuid and sled-uuid optional

- Cargo.lock
- Cargo.toml
- mg-lower/src/dendrite.rs
We've observed that calls over `AF_ROUTE` sockets to `RTM_GET` (see `routing(4p)`) can go unanswered. This patch makes it so we don't wait indefinitely in such situations. A timeout of 1 second is set for `AF_ROUTE` calls. This code is in a reconciler sync path, so transient failures are handled by the nature of the execution pattern.
> add timeout to kernel route get request

- Cargo.toml
Noticed that we were pulling in a dependency on uuid 0.8 in omicron -- I think
this should be uuid1.
> [deps] depend on uuid1, not uuid (which implies uuid08)

- Cargo.lock
- Cargo.toml
Looks like #199 rolled the opte version back to the previous commit, breaking omicron#5568 once I rebased on `main` over there. I figure this was probably necessary for our most recent release, so now I'm bumping this back to the latest version of opte.
> bump opte again

- Cargo.lock
- Cargo.toml
This is needed to support oxidecomputer/omicron#5602.
I'm leaving in draft for now so as not to block any other maghemite updates -- I'm aiming to merge after oxidecomputer/omicron#5722.
> Bump OPTE to API version 0.31

- .github/buildomat/jobs/test-ddm-trio-v1-server.sh
- .github/buildomat/jobs/test-ddm-trio-v1-transit.sh
Relevant to #275. My inclination is to remove dead code and pick it back up from the git history, but @rcgoodfellow asked that we disable it instead. See #275 for a fuller explanation, but in short, these tests validate against v1 which is no longer relevant given that upgrade from v1 is no longer supported.
> disable the ddm v1 tests

- Cargo.lock
- Cargo.toml
This is a pre-requisite for oxidecomputer/omicron#5777. As always, we may want to hold merging this until all approvals of that PR are in to avoid blocking bugfixes to maghemite.
> Update OPTE to 0.32.265.

- .github/buildomat/jobs/test-ddm-trio-v2-server.sh
- .github/buildomat/jobs/test-ddm-trio-v2-transit.sh
- .github/buildomat/jobs/test-ddm-trio.sh
- .github/buildomat/test-ddm-common.sh
- Cargo.lock
- ddm/src/discovery.rs
- ddm/src/exchange.rs
- mg-common/src/net.rs
- tests/Cargo.toml
- tests/src/ddm.rs
This PR provides compatibility between DDM exchange protocol versions 2 and 3. When the transition to `oxnet` data structures took place, some members of data structures in the DDM exchange API were changed. In particular, members representing IPv4 and IPv6 prefixes. Because the `oxnet` data structures (de)serialize differently than the bespoke data structures that were there before, an incompatibility across DDM versions was introduced. 
This PR brings back the basic IP prefix data structures that were in use before and provides both V2 and V3 exchange API methods. Like prior cross-compatibility between V2 and V1, the version of a peer is determined during discovery, and then the exchange protocol implementation will use the appropriate method versions and deserialization mechanisms …
> compat between ddm exchange protocol v2/v3

- bgp/src/session.rs
- mgd/src/bgp_admin.rs
- mgd/src/bgp_param.rs
- Fixes #291
- Fixes deadlock in `ExportPolicyChanged` handler in the `established` state
> apply changes to peers on `bgp_apply`

- bgp/src/messages.rs
> Only use AS_TRANS when ASN is not 2-octet mappable

- Cargo.lock
- Cargo.toml
Removal of VNICs from OPTE is a fairly breaking change, so has a new API version number. This PR bumps the OPTE version here as part of https://github.com/oxidecomputer/omicron/pull/5989.
> Update OPTE to v0.33.277

- ddm/src/admin.rs
- ddm/src/oxstats.rs
- ddmd/src/main.rs
- ddmd/src/smf.rs
- mg-common/src/nexus.rs
- mg-common/src/smf.rs
- mgd/src/main.rs
- mgd/src/oxstats.rs
- mgd/src/smf.rs
- Fixes #304
- Use the IPv6 underlay address for the producer server to resolve Nexus internally, rather than providing it or resolving it once on startup
- Some cleanup and removal of unused methods
> Let the oximeter producer server use DNS all the time

- mgadm/src/bgp.rs
Hit this issue doing some debugging.
```
$ ./target/debug/mgadm bgp config origin ipv4 create
thread 'main' panicked at /home/ry/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.5.10/src/builder/debug_asserts.rs:638:17:
Found non-required positional argument with a lower index than a required positional argument: "prefixes" index Some(1)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Abort (core dumped)
```
This PR fixes the issue described above.
> fix originate4 cli arg ordering

- bgp/src/session.rs
- mgadm/src/bgp.rs
- mgadm/src/static_routing.rs
- mgd/src/main.rs
- mgd/src/static_admin.rs
- openapi/mg-admin.json
- rdb/src/bestpath.rs
- rdb/src/db.rs
- rdb/src/lib.rs
- rdb/src/types.rs
This primarily makes 5 changes:
1. Move BGP's `local_pref` into `BgpPathProperties` (this is a BGP-specific attribute, let's store it with the other BGP-specific attributes)
2. Rename the RIB's `local_pref` to `rib_priority` (since this is used by the RIB to prioritize certain protocols/paths over others)
3. Fixes up tests to use the new nomenclature/structure
4. Introduces new constants to represent default RIB priorities for Static and BGP protocols
5. Enables RIB priority comparison in the RIB's bestpath selection algorithm
> RIB Priority Changes

- mgd/src/bgp_admin.rs
> mgd: cleanup routes from deleted bgp peer

- .github/buildomat/jobs/test-rdb.sh
- rdb/src/db.rs
The closure in remove_bgp_prefixes() was incorrectly returning false when Path.bgp was None.  This caused static route paths to be incorrectly deleted during BGP path deletion.
> Fix BGP route deletion and enable rdb tests in CI

- bgp/src/session.rs
Both session_setup() and handle_refresh() are methods that are specific to a single peer.  These should not be calling send_all(), since that results in an update being sent to all peers (including the one we're already about to call send_update() for).
Fixes: #403
> bgp: don't call send_all() upon single peer events

- Cargo.lock
- Cargo.toml
OPTE has had an API version bump due to the movement of several types (e.g., VNIs) downstream into ingot, as well as conversion from `core::net::IpAddr` for internal IP address types. This PR bumps the ioctl library versions as a prerequisite for merging into omicron.
> Chore: Bump version for OPTE.

- Cargo.lock
- Cargo.toml
- ddm/src/oxstats.rs
- mg-common/Cargo.toml
- mg-lower/src/dendrite.rs
- mgd/src/oxstats.rs
Update oxnet to 0.1.0 from crates.io. Also update omicron and dendrite to pull
in compatibility changes.
There are a lot of changes here unfortunately. I've tried to minimize changes
(in particular I didn't also update dropshot in this repo).
Aiming to land this after r13.
> update oxnet, omicron, dendrite

- ddm/src/admin.rs
- openapi/ddm-admin.json
Small housekeeping PR: I was doing some unrelated work in sled-agent and noticed these two parameters are no longer needed to start the Oximeter server, so I think we can safely drop them. This should be backwards-compatible, since an old client sending these params is fine (we'll just ignore them), and we only receive these, never send them.
> [ddm-admin] Remove now-unused parameters when starting Oximeter server

- Cargo.lock
- Cargo.toml
This revision is consistent with the current omicron main (https://github.com/oxidecomputer/omicron/blob/d9f7ebbef1b8ddfe73d268d821bde0c22e986dc1/Cargo.toml#L523).
> Bump opte-ioctl

- .github/buildomat/jobs/build.sh
- .github/buildomat/jobs/image.sh
- .github/buildomat/jobs/linux.sh
- .github/buildomat/jobs/p5p.sh
- .github/buildomat/jobs/test-bfd.sh
- .github/buildomat/jobs/test-bgp.sh
- .github/buildomat/jobs/test-ddm-quartet.sh
- .github/buildomat/jobs/test-ddm-trio.sh
- .github/buildomat/jobs/test-rdb.sh
- .github/buildomat/test-ddm-common.sh
- Cargo.lock
- Cargo.toml
- ddm/Cargo.toml
- ddm/src/sys.rs
- mg-lower/Cargo.toml
- mg-lower/src/dendrite.rs
- mg-lower/src/lib.rs
- tests/src/ddm.rs
Use the exported `types::PortId` rather than dendite's internal `common::ports::PortId`.
Update the dendrite commit used for testing, and adapt to the new dendrite/smf interaction.
> Bump dendrite

- mgd/src/static_admin.rs
update the behavior of `mgadm static get-v4-routes` to only return entries found in the persistent sled db, rather than querying the entire rib and trying to filter out all the bgp prefixes.
Fixes: #465
> mgd: return sled db instead of static rib

- Cargo.lock
- Cargo.toml
- ddm/src/exchange.rs
- rdb/src/bestpath.rs
- rust-toolchain.toml
- tests/src/ddm.rs
Brings us up to OPTE v0.35.x, and is part of bringing tunnelled LSO into use by omicron.
An extra point is that I needed to bump the rust version used in this repo, since OPTE is on the 2024 rust edition. Renovate has opened a PR for this at some point, but it has languished for some time.
> Chore: Bump OPTE to `88adb1a`

- Cargo.lock
- Cargo.toml
- ddm/src/sys.rs
Pulling this in here before omicron since we have an API version bump. The only meaningful change in maghemite is that `OpteHdl`s are constructed using a simple `::new()` now.
> Update OPTE to 0.36.374

- Cargo.lock
- Cargo.toml
As in the title, updates OPTE to the latest version on `main`. This is a prerequisite for https://github.com/oxidecomputer/omicron/pull/8194 due to the `API_VERSION` increment.
> Bump OPTE to v0.37.383

- Cargo.lock
- Cargo.toml
- clippy.toml
- ddmadm/Cargo.toml
- ddmadm/src/main.rs
- ddmd/Cargo.toml
- ddmd/src/main.rs
- lab/Cargo.toml
- lab/src/2x2/main.rs
- lab/src/duo/main.rs
- lab/src/quartet/main.rs
- lab/src/solo/main.rs
- lab/src/trio/main.rs
- mg-ddm-verify/Cargo.toml
- mg-ddm-verify/src/main.rs
- mgadm/Cargo.toml
- mgadm/src/main.rs
- mgd/Cargo.toml
- mgd/src/main.rs
- package/src/main.rs
As described in [RFD 579], we are now recommending certain non-default Tokio runtime configurations in all software we deploy in production. The [`oxide-tokio-rt`] crate provides a way to easily get these common recommended configurations by using its functions to initialize the runtime rather than `#[tokio::main]`
Presently, `oxide-tokio-rt` does the following:
- Enables DTrace probes for Tokio runtime events using [`tokio-dtrace`]
- Disables the [LIFO slot optimization][lifo], which was the root cause of omicron#8334
But, we anticipate that if there are additional Tokio configurations which we want to recommend in the future, we'll add them here as well.
This commit updates `maghemite` to initialize the Tokio runtime using `oxide-tokio-rt`. I've added a Clippy config for warning on uses …
> Use `oxide-tokio-rt` rather than `#[tokio::main]`

- mgadm/src/bestpath.rs
- mgadm/src/main.rs
- mgd/src/bgp_admin.rs
- mgd/src/bgp_param.rs
- openapi/mg-admin.json
- rdb/src/db.rs
- rdb/src/error.rs
Adds an API endpoint for /bestpath/fanout and methods to get/set the fanout value.  This defines the maximum number of ECMP paths that can be selected by the RIB during bestpath calculation.
Fixes: #400
> Add bestpath fanout config capabilities
